---
title: "Organization of my study"
author: "Naoya Hieda"
date: "`r Sys.Date()`"
output:
  pdf_document:
    latex_engine: lualatex
documentclass: ltjsarticle
mainfont: Meiryo
monofont: Meiryo

---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# 去年の研究の過程

1. 粒子フィルタリングによるDefautlRateの密度関数の推定  
日本のデフォルトデータと米国のデフォルトデータ、それぞれで行った。
この時点で、Hullの本で紹介される密度関数に従う分布で推定を行うと、$\rho$が0に近いとき
尤度が発散してしまうので、PDと$\rho$の推定を同時に行えないことが判明($\rho$が0に向かってしまう)

以降、実際のデータに適用する前に、シミュレーションでデフォルト率を発生させて適用している

2. PDと$\rho$にモデルを仮定(AR)  
同時に推定が行えないことが判明したので、PDと$\rho$にARモデルを仮定し、挙動を制限することで、同時に推定できないかという試み。結論としては、ARモデルのパラメータによって、シミュレーションで発生するPDと$\rho$が全く違うので、そこを考慮する必要があるとなった  
また、同時推定で、$\rho$が0に向かわないようなパラメータ(ARモデルの分散を小さく)にすると、シミュレーションの状態変数の挙動が小さくなってしまった(PDなら0.034から0.045 DRなら)

3. Liu&West(補助粒子フィルタ)  
ARモデルのパラメータの推定が必要になったため、利用したアルゴリズム  
また、PDか$\rho$を固定した場合、もう片方の推定はパラメータとして推定できる(定数扱い)。基本的な考え方は粒子フィルタと同じで、全てのパラメータは正規分布に従うと考える。  
一応、収束して、それらしい値になっているが、初期値に実際のパラメータを与えたり、ばらつき(探索範囲?)をかなり小さくなどしているので、問題は山積み

4. 提案分布(重点分布)を実際の分布にする  
なんでやったのか忘れました・・・たぶん、ARモデルがうまくおえなかったため。以降、基本的にこれなので、粒子フィルタではなく、モンテカルロフィルタになっている。

5. 平滑化(Forward Filtering Backward Smoothing)  
予測を行うには平滑化が必要ということで行った。ParticleFilterの平滑化の方法の一つ。  
他にも方法はあるが、今のところこのアルゴリズムしか試していない  
これの一回当たりの実行時間が長い(当初3日、改善して数時間)

6. PDと$\rho$にモデルを仮定(Local Trend)  
2のARモデルより、PDと$\rho$の挙動として自然なんじゃないか  
$\rho=0$を避けるのもこちらのほうが良いのではないかということで実装  
ファイルを確認している限り、同時推定を行っていない。  
これの$\rho$固定で3,5を行ったものを去年の論文に乗せている。

7. DefaultRateに同時分布を仮定  
日本の実際のデフォルトデータとシミュレーションで発生させたデフォルトの挙動が明らかに違うため、
そもそも実際のデフォルトは、前期のデフォルトをひきづっているのではないか。ということで、同時分布を仮定して推定した。  
こちらは、発生させるところまでは行ったが、実際のデータがそもそも過去1年の平均をその月のデフォルトとしており、そちらを何とかしなくてはならないのではないかという方向に。

8. EMアルゴリズム  
フィルタリングと平滑化を連続で行う事で、モデルのパラメータを推定したいという話。  
平滑化に時間がかかりすぎるため実装できないまま。

9. IF(Iterated Filtering)とPMCMC(Particle Markov Chain Monte Carlo)の実装  
論文に乗せた話 IFは一度理解。PMCMCはアルゴリズムの理解と実装までは行えた。  

# 今年行ったこと(試みていること)

1. Dynamic Default Rates(Robert Lamb William Perraudin 2008) 和訳と実装  
上記論分にて、Hullの式とは違うデフォルト率分布が定義されているので、その和訳と再現。
デフォルト率そのものをARモデルに従うと考えていた。このモデルで状態空間モデルを考える・・・という話だった。  
論文に従うならカットオフポイント(マートンモデルのデフォルト閾値)を状態変、相関係数をパラメータ扱いで状態空間モデルになりそう。  
再現はデータがそろわない、最適化の仕方がわからないなどの理由で最後までは行かなかった。

2. GPUでParticleFilter実装の準備  
GPUでParticleFilterを実装するためのアルゴリズム調査  
Disributed Computation Paticle Filters on GPU Architectures for Real-Time Conrol Applicationsという論文の導入と1章の和訳。サブフィルタを用いて行うらしい。

3. 重点サンプリングの確認  
粒子フィルタを行う上で基礎となっている重点サンプリングの確認。Rによるモンテカルロ法の2,3章実装

4. Strong Consistency of the Maximum Likelihood Estimator for Finite Mixtures of Location-Scale Distributions When Penalty is imposed on the Ratios of the Scale Parameters  
$\rho=0$に、ならないように、ペナルティ付き尤度を考える。2章の和訳途中  

# 現状の課題

1. EMを実行するための計算時間

2. Particleの数は何個必要か

3. 提案分布をどうするか

4. モデルをどうするか

5. PDと$\rho$を同時に推定するにはどうすればいいか

6. そもそもモンテカルロフィルタになっている。

7. 日本のデータが移動平均のようなものだがこれで推定しても問題ないのか